name: Linting

on:
  push:
    branches:
      - master
    paths:
      - '**.tf'

  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform:
    name: Terraform format and validate
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.26

    - name: terraform fmt
      run: terraform fmt -check -recursive -diff

    - name: 'module: terraform init'
      run: terraform init

    - name: 'samples: terraform validate'
      env:
        AWS_DEFAULT_REGION: eu-central-1
      run: |
        for sample in $(find samples -maxdepth 1 -mindepth 1 -type d); do
          cd $sample
          terraform init
          terraform validate
          cd -
        done

  docs:
    name: Docs
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: brew update && brew install pre-commit terraform-docs terraform

    - name: Verify docs up-to-date
      run: pre-commit run --show-diff-on-failure --all-files terraform_docs

